version: '3.3'

services:
  web:
    image: cih2001/actions-ocean-web:latest
    ports:
      - "80:1234"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    depends_on:
      - watchtower
    environment:
      DBUSERNAME: ${MONGO_USERNAME}
      DBPASSWORD: ${MONGO_PASSWORD} 

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: mongod --auth
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 30s
      timeout: 10s
      retries: 5
      # logging:
      # driver: none # Disable mongo logs.

  watchtower:
    image: containrrr/watchtower
    command: --label-enable --cleanup --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
