name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...
      
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout code.
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build main.go
    
    - name: Build & Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cih2001/actions-ocean-web
        tags: latest
        registry: docker.io
        dockerfile: ./Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
